# Generated by Django 5.2.6 on 2025-09-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='password',
        ),
    ]
