# Generated by Django 5.2.6 on 2025-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_contestant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
