# Generated by Django 5.2.6 on 2025-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contestant_is_winner_contestant_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='is_winner',
        ),
    ]
