# Generated by Django 5.2.6 on 2025-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_remove_contestant_is_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='password',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
