# Generated by Django 5.2.6 on 2025-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_contestant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
