FROM node:20-alpine

WORKDIR /app

COPY frontend/app-sv/package*.json ./

RUN npm install
COPY frontend/app-sv/ ./

RUN npm run build

RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "5173"]
