services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5050"
    volumes:
      - ./backend/db:/app/db
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend/db:/app/db
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"


