FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY backend/ .

RUN mkdir -p /app/db && chmod 777 /app/db

RUN adduser --disabled-password djangouser
USER djangouser

CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:5050"]

